# Generated by Django 2.0.6 on 2018-06-20 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docfinder', '0006_auto_20180618_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
