# Generated by Django 2.0.6 on 2018-06-25 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docfinder', '0008_auto_20180624_0123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insurance',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='specialty',
            name='doctor',
        ),
        migrations.AddField(
            model_name='doctor',
            name='insurances',
            field=models.ManyToManyField(to='docfinder.Insurance'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='specialties',
            field=models.ManyToManyField(to='docfinder.Specialty'),
        ),
    ]
