# Generated by Django 2.0.6 on 2018-06-28 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docfinder', '0009_auto_20180624_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
