# Generated by Django 2.0.6 on 2018-06-28 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docfinder', '0011_auto_20180628_0023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='insurances',
            field=models.ManyToManyField(blank=True, to='docfinder.Insurance'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='specialties',
            field=models.ManyToManyField(blank=True, to='docfinder.Specialty'),
        ),
    ]
